### PR TITLE
Fix missing nzbget.h includes causing compilation errors

### PR DESCRIPTION
**Pull request by sbraz**
## Description

Hi,
While building nzbget 26.0 for Gentoo, I ran into build problems that I couldn't reproduce when building nzbget manually from the git repo. If you know why, please let me know, I'm curious as to how this slipped past the CI.

Include nzbget.h before other headers in UrlCoordinator.cpp (broken since 0fbd1b5d2fce4e353d2a5ea18e8a75cd708a4335, I assume) and PathsValidator.cpp to ensure functions and types are properly declared before use.

Without this fix, compilation fails with errors like:
```
/var/tmp/portage/net-nntp/nzbget-26.0/work/nzbget-26.0/daemon/queue/UrlCoordinator.cpp:208:25: error: ‘error’ was not declared in this scope
  208 |                         error("Cancelling hanging url download %s", urlDownloader->GetInfoName());
      |                         ^~~~~
```
```
/var/tmp/portage/net-nntp/nzbget-26.0/work/nzbget-26.0/daemon/util/NString.h:67:17: error: ‘free’ was not declared in this scope
   67 |                 free(m_data);
      |                 ^~~~
```

## Lib changes

None

## Testing

Build nzbget.

### CODE REVIEW

**Review by dnzbk — APPROVED** [review]

**Comment by dnzbk** [comment]
Thanks, merging this now.

I'm not sure about the CI, as it worked fine when I manually built the app on macOS, Debian and Windows. 
It might be a side effect of PCH (Precompiled Headers), but that's just a guess.

**Comment by sbraz** [comment]
> It might be a side effect of PCH (Precompiled Headers), but that's just a guess.

Thanks, it was indeed. I reproduced by checking out the repo before my patch and rebuilding with `cmake -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON`. Gentoo does that here: https://github.com/gentoo/gentoo/blob/551f40ce2094e810bf60e8c1b817d30a9f66d8bb/eclass/cmake.eclass#L661

Maybe the CI should run with this option too?

**Comment by dnzbk** [comment]
>Maybe the CI should run with this option too?

I'll definitely think about that, thanks for the suggestion.
