### ISSUE TITLE
HEAD - Failing test in FeedTests

### ISSUE THREAD

**Issue by bket** [nzbgetcom/nzbget#572]
### Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### NZBGet Version

latest-testing (if not listed here)

### Platform

All

### Environment

```markdown
OS Version: OpenBSD kerberos.lan 7.7 GENERIC.MP#128 amd64

Using boost-1.87.0 and libxml-2.14.3.
```

### Current Behavior

FeedTests fails a test:

```
test 2
    Start 2: FeedTests

2: Test command: /usr/ports/pobj/nzbget-25.0.20250523/build-amd64/tests/feed/FeedTests "--log_level=message"
2: Working Directory: /usr/ports/pobj/nzbget-25.0.20250523/build-amd64/tests/feed
2: Test timeout computed to be: 1500
2: Running 2 test cases...
2: game
2: games
2: gam
2: gam*
2: am*
2: *am*
2: game of clowns
2: game of clown
2: game of clown*
2: game.of?clowns
2: game*of*clowns
2: game*of*clowns*
2: *game*of*clowns*
2: game of clowns WEB-DL
2: game of clowns -WEB-DL
2: +title:@game
2: -game
2: -kings
2: title:game.of.clowns size:<4GB
2: title:game.of?clowns
2: @game
2: size:<1.4GB
2: HDTV category:*hd* -badgroup s02e* size:>600MB size:<2000MB
2: size:<2000MB
2: age:<10
2: age:<=10
2: age:>1h
2: age:>=1h
2: $game.*\.s02e[0-9]*\..*
2: R:  game  of
2: A(category:my series, pause:yes, priority:100):game
2: A(c:my series, p:n, r:100, s:1000, k:1080p):game
2: A(my series, paused, 100):game
2: A(k:series=GOT-${1}-${2}): Game of clowns S##E##
2: A(k:series=GOT-${1}-${2}): $.+S([0-9]{1,2})E([0-9]{1,2})
2: /usr/ports/pobj/nzbget-25.0.20250523/nzbget-61fe70e2071be4be61a15e7ebf598514f3b8ae05/tests/feed/FeedFileTest.cpp(49): error: in "FeedFileTest": check feedInfo.GetDescription() == std::string("   Title:     Test.Title         Added to index:     09/05/2025 14:05:12         Weblink:     N/A") has failed [ !=    Title:     Test.Title         Added to index:     09/05/2025 14:05:12         Weblink:     N/A]
2:
2: *** 1 failure is detected in the test module "FeedTest"
2:
2/8 Test #2: FeedTests ........................***Failed    0.04 sec
```

### Expected Behavior

Expected behaviour is that all tests pass.

### Steps To Reproduce

Can be reproduced in this environment by running `ctest -V`.

### Extra information

Reverting 98bb21957e2f8c0eb40d3b1ea195725e6b2450c2 fixes this issue for me.

**Comment by bket** [comment]
The failing test in FeedTests seems to be persistent, at least in my case, even after rebuilding and re-running multiple times. I can confirm that NNTPTests fails sporadically. 

So far I have found that `m_tagContent` is always empty in https://github.com/nzbgetcom/nzbget/blob/develop/daemon/feed/FeedFile.cpp#L210

I will dig a bit deeper.

**Comment by dnzbk** [comment]
> So far I have found that m_tagContent is always empty in https://github.com/nzbgetcom/nzbget/blob/develop/daemon/feed/FeedFile.cpp#L210
I will dig a bit deeper.

Thank you.

**Comment by bket** [comment]
Found the issue I experienced:
- OpenBSD current has libxml-2.14 in ports while OpenBSD-7.6 and OpenBSD-7,7 have libxml-2.13
- In libxml2 2.13 and earlier, CDATA content is delivered through the characters() callback - so no special handling needed.
- Starting with libxml2 2.14, CDATA content is reported via the new cdataBlock() callback, separately from characters().
- However, if cdataBlock is not set, CDATA data still falls back to characters(), but potentially fragmented.

As I'm running OpenBSD current with libxml-2.14 I experienced fragmentation causing the specific test to fail. This is a new failure as https://github.com/nzbgetcom/nzbget/commit/98bb21957e2f8c0eb40d3b1ea195725e6b2450c2 introduced `[CDATA]` to `tests/testdata/feed/feed.xml`.

Issue is not observed on OpenBSD-7.6 and OpenBSD-7.7 because of the older libxml in ports.

I have a fix for this, which I will open a PR.
